trivia = [
    ['What is the capital of France?', ['Paris', 'Rome', 'Berlin', 'Madrid']],
    ['Which planet is known as the Red Planet?', ['Mars', 'Venus', 'Jupiter', 'Mercury']],
    ['Who created Minecraft?', ['Markus Persson', 'Bill Gates', 'Elon Musk', 'Tim Sweeney']],
    ['Which country is famous for sushi?', ['Japan', 'China', 'Thailand', 'Vietnam']],
    ['What is the largest ocean on Earth?', ['Pacific Ocean', 'Atlantic Ocean', 'Indian Ocean', 'Arctic Ocean']],
    ['Which animal is known as the King of the Jungle?', ['Lion', 'Tiger', 'Elephant', 'Bear']],
    ['What color do you get by mixing red and blue?', ['Purple', 'Green', 'Orange', 'Brown']],
    ['How many continents are there?', ['7', '5', '6', '8']],
    ['What is the tallest animal in the world?', ['Giraffe', 'Elephant', 'Camel', 'Horse']],
    ['Which company created the iPhone?', ['Apple', 'Samsung', 'Google', 'Nokia']],
    ['Who painted the Mona Lisa?', ['Leonardo da Vinci', 'Vincent van Gogh', 'Pablo Picasso', 'Claude Monet']],
    ['Which country has the most people?', ['India', 'China', 'United States', 'Indonesia']],
    ['What is the freezing point of water in Celsius?', ['0', '32', '100', '-10']],
    ['Which superhero is known as the Dark Knight?', ['Batman', 'Superman', 'Iron Man', 'Spider-Man']],
    ['What is the biggest mammal?', ['Blue Whale', 'Elephant', 'Giraffe', 'Hippo']],
    ['Which game features blocks and creepers?', ['Minecraft', 'Roblox', 'Terraria', 'Fortnite']],
    ['What is the capital of Australia?', ['Canberra', 'Sydney', 'Melbourne', 'Perth']],
    ['Which sport uses a racket and a shuttlecock?', ['Badminton', 'Tennis', 'Squash', 'Ping Pong']],
    ['How many days are in a leap year?', ['366', '365', '364', '367']],
    ['Which gas do plants absorb?', ['Carbon Dioxide', 'Oxygen', 'Nitrogen', 'Hydrogen']],
    ['Who lives in a pineapple under the sea?', ['SpongeBob SquarePants', 'Patrick Star', 'Squidward', 'Plankton']],
    ['Which Pokémon is number 25?', ['Pikachu', 'Charmander', 'Bulbasaur', 'Eevee']],
    ['What is the currency of Japan?', ['Yen', 'Won', 'Dollar', 'Peso']],
    ['Which continent is Egypt in?', ['Africa', 'Asia', 'Europe', 'South America']],
    ['Which bird cannot fly?', ['Penguin', 'Eagle', 'Parrot', 'Sparrow']],
    ['What is the hardest natural substance?', ['Diamond', 'Gold', 'Iron', 'Quartz']],
    ['Which social media platform has the logo of a ghost?', ['Snapchat', 'Instagram', 'TikTok', 'Facebook']],
    ['Which movie features the quote "I am your father"?', ['Star Wars', 'Harry Potter', 'The Matrix', 'Avengers']],
    ['Which country is famous for pizza?', ['Italy', 'France', 'Mexico', 'Greece']],
    ['How many sides does a hexagon have?', ['6', '5', '7', '8']],
    ['Which is the fastest land animal?', ['Cheetah', 'Lion', 'Horse', 'Leopard']],
    ['Who wrote "Harry Potter"?', ['J.K. Rowling', 'Stephen King', 'J.R.R. Tolkien', 'George R.R. Martin']],
    ['What is the smallest prime number?', ['2', '1', '3', '5']],
    ['Which language is mainly spoken in Brazil?', ['Portuguese', 'Spanish', 'English', 'French']],
    ['Which app is known for short dance videos?', ['TikTok', 'WhatsApp', 'Discord', 'Telegram']],
    ['Which company makes PlayStation?', ['Sony', 'Nintendo', 'Microsoft', 'Sega']],
    ['What is the chemical symbol for gold?', ['Au', 'Ag', 'Gd', 'Go']],
    ['Which country gifted the Statue of Liberty to the USA?', ['France', 'England', 'Germany', 'Canada']],
    ['Which meme dog became the face of Dogecoin?', ['Doge', 'Grumpy Cat', 'Nyan Cat', 'Keyboard Cat']],
    ['Which is the largest planet?', ['Jupiter', 'Saturn', 'Earth', 'Neptune']],
    ['Which ocean lies between Africa and Australia?', ['Indian Ocean', 'Pacific Ocean', 'Atlantic Ocean', 'Arctic Ocean']],
    ['Who is Mario\'s brother?', ['Luigi', 'Wario', 'Toad', 'Yoshi']],
    ['Which fruit keeps the doctor away according to the saying?', ['Apple', 'Orange', 'Banana', 'Pear']],
    ['What is the main ingredient in guacamole?', ['Avocado', 'Tomato', 'Cucumber', 'Lettuce']],
    ['Which country is home to the kangaroo?', ['Australia', 'New Zealand', 'South Africa', 'Canada']],
    ['Which game has the phrase "Victory Royale"?', ['Fortnite', 'PUBG', 'Valorant', 'Apex Legends']],
    ['Which is the longest river in the world?', ['Nile', 'Amazon', 'Yangtze', 'Mississippi']],
    ['What does "LOL" stand for?', ['Laugh Out Loud', 'Lots Of Love', 'League Of Legends', 'Laughing On Loop']],
    ['Which is the largest desert in the world?', ['Antarctica', 'Sahara', 'Arabian', 'Gobi']],
    ['Who created Facebook?', ['Mark Zuckerberg', 'Steve Jobs', 'Larry Page', 'Jeff Bezos']]
]